#!/bin/bash
chmod +x up.sh
chmod +x down.sh
docker build -t vpn-proxy1 .
exec docker run \
    --name=vpn-proxy1 \
    --rm \
    --tty \
    --interactive \
    --device=/dev/net/tun \
    --cap-add=NET_ADMIN \
    --publish 0.0.0.0:6001:1080 \
    vpn-proxy1:${TAG:-latest}
